apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sim-exporter.fullname" . }}-config
  labels:
  {{- include "sim-exporter.selectorLabels" . | nindent 4 }}
data:
  {{- range .Values.configFiles }}
  {{ base . }}: |-
    {{- $.Files.Get . | nindent 4 }}
  {{- end }}