apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sim-exporter.fullname" . }}-config
  labels:
  {{- include "sim-exporter.selectorLabels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.configs }}
  {{ $k }}: |-
    {{- $v | nindent 4 }}
  {{- end }}