variables:
  # General ALM debugging, causes "set -x" behaviour in ALM shell scripts
  #ALM_DEBUG: "true"

  # Default: "make --trace". We need to specify a target because the default
  # target is meant for local development
  GO_BUILD_COMMAND: "make alm_build"

  # Disable unit tests because they require a ./pkg/... structure
  DISABLE_GO_UNIT_TESTS: "true"

  # Disabling SonarQube code quality checks. Saves ~10s but should not
  # usually be disabled
  #DISABLE_SONAR: "true"

  # Suggested by https://confluence.gec.io/display/SOFT/ALM+Build+Usage+Guide
  DISABLE_HELM_INTEGRATION_TEST_JOB: "true"

  # Force version bumps for changes on default branch instead of just bumping
  # on non-default branches
  FORCE_MASTER_VERSION_BUMPS: "true"

  # Set the default git branch (default: "master")
  # MAIN_BRANCH: "main"

  # Use docker instead of default "podman". Adds ~10s build time because a
  # docker daemon is started
  #DOCKER_BUILD_TOOL: "docker"

  # Suggested to be faster than default "vfs" on https://confluence.gec.io/pages/viewpage.action?pageId=113479785
  # Currently irrelevant for our purpose
  #STORAGE_DRIVER: "overlay"

  # Disable irrelevant build logic
  DISABLE_MAVEN_DEPLOY: "true"
  DISABLE_GRADLE_DEPLOY: "true"
  DISABLE_PYTHON_DEPLOY: "true"
  DISABLE_SETUPTOOLS_DEPLOY: "true"


include:
  project: "alm/common-infrastructure/gitlab-ci-templates"
  ref: master
  file: '.go-docker.yml'

# Analyze package-and-publish phase
#docker-debug:
#  stage: package-and-publish
#
#  extends: .base-job
#
#  script:
#    - "env"
#    - "echo pwd:$(pwd)"
#    - "ls -la /"
#    - "find /build* -type f"
#    - "cd /builds/operations-center/operationscenter-observability/observability-cli"
#    - "ls -la"
#    - "find build -ls"
