apiVersion: v2
name: sim-exporter
description: A prometheus metric simulator

type: application

# Proper version is injected through ALM
version: 0.0.0

# Proper version is injected through ALM
appVersion: 0.0.0
